[package]
name = "tw3-mod-settings-framework-parser"
version = "1.0.1"
edition = "2021"

[[bin]]
name    = "settings_parser"
path    = "src/main.rs"


[dependencies]
roxmltree = "0.14.1"
clap = { version = "^3.0", features = ["derive"] }
