name: check-build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build parser
      uses: ./.github/actions/build-parser
    - name: Run tests
      run: cargo test --verbose
      working-directory: ./settings-parser