name: draft-release

on:
  push:
    tags: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  parser:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true
    - name: Build with Cargo
      run: cargo build --release --target=x86_64-pc-windows-msvc
      working-directory: ./settings-parser

    - name: Zip parser
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: "${{ github.workspace }}/TW3_MSF_Parser.zip"
        path: "settings_parser.exe"
        directory: "./settings-parser/target/x86_64-pc-windows-msvc/release"

    - uses: actions/upload-artifact@v4
      with:
        name: parser
        path: "TW3_MSF_Parser.zip"


  scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Remove manifests locally to not include them in released packages
      run: find . -type f -name "witcherscript.toml" -delete

    - name: Zip modSettingsFramework
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: "${{ github.workspace }}/TW3_MSF_modSettingsFramework.zip"
        path: "modSettingsFramework"

    - name: Zip v1.32 hooks
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: "${{ github.workspace }}/TW3_MSF_Hooks_1.32.zip"
        path: "modSettingsFrameworkHooks"
        directory: "./hooks/v1.32"
    - name: Zip v4.00 hooks
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: "${{ github.workspace }}/TW3_MSF_Hooks_4.00.zip"
        path: "modSettingsFrameworkHooks"
        directory: "./hooks/v4.00"
    - name: Zip v4.03 hooks
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: "${{ github.workspace }}/TW3_MSF_Hooks_4.03.zip"
        path: "modSettingsFrameworkHooks"
        directory: "./hooks/v4.03"
    - name: Zip v4.04 hooks
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: "${{ github.workspace }}/TW3_MSF_Hooks_4.04.zip"
        path: "modSettingsFrameworkHooks"
        directory: "./hooks/v4.04"
    - name: Zip v4.04a_REDkit+ hooks
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: "${{ github.workspace }}/TW3_MSF_Hooks_4.04a_REDkit+.zip"
        path: "modSettingsFrameworkHooks"
        directory: "./hooks/v4.04a_REDkit+"

    - name: Zip samples
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: "${{ github.workspace }}/TW3_MSF_Samples.zip"
        path: "samples"

    - uses: actions/upload-artifact@v4
      with:
        name: scripts
        path: "*.zip"

  release:
    runs-on: ubuntu-latest
    needs: [parser, scripts]
    if: success() 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: "./artifacts"
        merge-multiple: true

    - name: Create draft release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/*.zip"
        draft: true
        generateReleaseNotes: true