name: draft-release

on:
  push:
    tags: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build parser
      uses: ./.github/actions/build-parser
    - name: Zip parser
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: "TW3_Mod_Settings_Framework_Parser.zip"
        path: "./settings-parser/target/x86_64-pc-windows-msvc/release/settings_parser.exe"
    - name: Zip modSettingsFramework
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: "TW3_Mod_Settings_Framework_modSettingsFramework.zip"
        path: "./modSettingsFramework"
    - name: Zip samples
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: "TW3_Mod_Settings_Framework_Samples.zip"
        path: "./samples"
    - name: Create draft release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "TW3_Mod_Settings_Framework_Parser.zip,TW3_Mod_Settings_Framework_modSettingsFramework.zip,TW3_Mod_Settings_Framework_Samples.zip"
        draft: true
        generateReleaseNotes: true