name: draft-release

on:
  push:
    tags: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true
    - name: Build with Cargo
      run: cargo build --release --target=x86_64-pc-windows-msvc
      working-directory: ./settings-parser
    - name: Zip parser
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: "TW3_MSF_Parser.zip"
        path: "./settings-parser/target/x86_64-pc-windows-msvc/release/settings_parser.exe"
    - name: Zip modSettingsFramework
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: "TW3_MSF_modSettingsFramework.zip"
        path: "./modSettingsFramework"
    - name: Zip samples
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: "TW3_MSF_Samples.zip"
        path: "./samples"
    - name: Create draft release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "TW3_MSF_modSettingsFramework.zip,TW3_MSF_Parser.zip,TW3_MSF_Samples.zip"
        draft: true
        generateReleaseNotes: true